name: Deploy

on:
  branches:
    - 'releases/**'
  release:
    types: [prereleased]

jobs:
  build_and_deploy_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          architecture: x64

      - name: COPY ENV
        run: cp .env.sample .env && cp .env.sample dotenv

      - name: Pub get
        run: flutter pub get

      - name: Generate l10n
        run: flutter gen-l10n

      - name: Build freezed models
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Enable web
        run: flutter config --enable-web

      - name: Build web
        run: flutter build web --release
        env:
          GEO_API_KEY: "${{ secrets.GEO_API_KEY }}"
          PLACE_API_KEY: "${{ secrets.PLACE_API_KEY }}"

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: wecount-2023
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
